package com.tigerlight.dad.util;

import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.DialogInterface;

/**
 * Created by M.T. on 7 Oct, 2016.
 * Purpose of this Class is to display different dialog in application for example : Progress Dialog, Information Dialog
 */
public class DisplayDialog {
    private static DisplayDialog ourInstance = new DisplayDialog();
    /**
     * A Progress Dialog object
     */
    private static ProgressDialog mDialog;

    private DisplayDialog() {
    }

    public static DisplayDialog getInstance() {
        return ourInstance;
    }
    //    private static ProgressDialog mDialog;

    /**
     * Displays the progress dialog on activity.
     * This method will generate progress dialog and displays it on screen if its not currently showing,
     * If the progressbar dialog already been showing than it will not generate new dialog and return old generated dialog.
     *
     * @param mContext     requires to create ProgressDialog in Application
     * @param message      displays the message on Progress Dialog
     * @param isCancelable Set cancelable property of progress dialog
     * @return Returns the object of Progress dialog that currently generated or previously generated.
     */
    public ProgressDialog showProgressDialog(final Context mContext, final String message, boolean isCancelable) {
        if (mDialog == null) {
            mDialog = new ProgressDialog(mContext);
        }
        if (!mDialog.isShowing()) {
            mDialog = new ProgressDialog(mContext);
            mDialog.show();
        }
        mDialog.setCancelable(isCancelable);
        mDialog.setCanceledOnTouchOutside(false);
        mDialog.setMessage(message);
        return mDialog;
    }


    /**
     * Dismiss Progress dialog if it is showing
     */
    public void dismissProgressDialog() {
        if (mDialog != null && mDialog.isShowing()) {
            mDialog.dismiss();
        }
    }


    /**
     * Displays information dialog on screen.
     * <p>
     * This method will display simple alert dialog on screen with message provided by user,
     * if the message is null or blank than it will not generate dialog.</p>
     *
     * @param mActivity requires for creating Alert Dialog Object.
     * @param message   displays message on dialog, must be not null and not empty.
     * @return Object of {link AlertDialog.Builder} that generated by this method.
     */
    public AlertDialog.Builder displayMessageDialog(final Context mActivity, final String message) {
        final AlertDialog.Builder dialog = new AlertDialog.Builder(mActivity).setMessage(message)
                .setPositiveButton(android.R.string.ok, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.dismiss();
                    }
                });
        dialog.show();
        return dialog;
    }
}
